spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:tstore.db
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true